/** Host services for the AI Coding platform plugin. */

export type * from './installer.ts'
export type * from './types.ts'
export type { Config } from './gateway.ts'
export type { WorkspaceGatewayConfig } from './workspace-gateway.ts'
export { TeamSkillInstallError, installTeamSkill, quarantineTeamSkill, uninstallTeamSkill } from './installer.ts'
export { TeamSkillHost } from './host.ts'
export { TeamSkillGateway } from './gateway.ts'
export { WorkspaceGateway } from './workspace-gateway.ts'
export { WorkspaceHost } from './workspace-host.ts'
export type { WorkspaceSessionProvider, WorkspaceHostOptions } from './workspace-host.ts'
export { TeamSkillKnowledgeLoop } from './knowledge-loop.ts'
export type { TeamSkillKnowledgeSelection, TeamSkillKnowledgeSearch } from './knowledge-loop.ts'
export { TeamSkillMemoryLoop } from './memory-loop.ts'
export type { TeamSkillMemoryCapture, TeamSkillMemoryCaptureRequest, TeamSkillMemoryRecall } from './memory-loop.ts'
export { CollectorController, TeamSkillTelemetryBackend } from './telemetry/backend.ts'
export { TelemetryProjection } from './telemetry/projection.ts'
export { TelemetryQueue, TelemetryStorageError, TELEMETRY_QUEUE_SCHEMA_VERSION } from './telemetry/queue.ts'
export { TelemetryReporter } from './telemetry/reporter.ts'
export type { TelemetrySend, TelemetrySendOutcome } from './telemetry/reporter.ts'
export { resolveTelemetrySettings } from './telemetry/settings.ts'
export { default } from './gateway.ts'
