/* Generated by `build/generate-remote-face.mjs` from the host gateways — do not edit.
 *
 * Upstream this file is emitted by `@deepseek-ai/dsh-typert-generator` as
 * `lib/typert.remote-client.d.ts`; that generator cannot run against this repository’s
 * single root-level package layout. See the script header and
 * `docs/typert-wiring-notes.md` for the evidence, and `tests/remote-face.spec.ts` for
 * the drift guard that keeps this file equal to a fresh run. */
import type { RemoteResult } from '@deepseek-ai/dsh-typert-protocol'
import type {
  CollectorAuthorizationState,
  CollectorFailure,
  CollectorMode,
  CollectorResult,
  CollectorSnapshot,
  CollectorStatus,
  TeamSkillAccessSummary,
  TeamSkillAccountMembership,
  TeamSkillAccountResult,
  TeamSkillAccountRole,
  TeamSkillAccountState,
  TeamSkillAccountStatus,
  TeamSkillAccountUser,
  TeamSkillAsset,
  TeamSkillAssetVisibility,
  TeamSkillAuditRole,
  TeamSkillAuthorizedArtifact,
  TeamSkillAuthorizedOperation,
  TeamSkillCatalog,
  TeamSkillCatalogItem,
  TeamSkillCatalogResult,
  TeamSkillChangePasswordRequest,
  TeamSkillEnvironment,
  TeamSkillFailed,
  TeamSkillInstallFailure,
  TeamSkillInstallRequest,
  TeamSkillInstallResult,
  TeamSkillInstallationRecord,
  TeamSkillInstallationView,
  TeamSkillKnowledgeBaseState,
  TeamSkillKnowledgeBaseSummary,
  TeamSkillKnowledgeBaseType,
  TeamSkillKnowledgeCitation,
  TeamSkillKnowledgePreview,
  TeamSkillKnowledgeSearchRequest,
  TeamSkillKnowledgeSearchResponse,
  TeamSkillKnowledgeSearchResult,
  TeamSkillKnowledgeSearchStatus,
  TeamSkillKnowledgeSelection,
  TeamSkillLoginRequest,
  TeamSkillMemory,
  TeamSkillMemoryAudit,
  TeamSkillMemoryJob,
  TeamSkillMemoryMutation,
  TeamSkillMemoryPage,
  TeamSkillMemoryRecallItem,
  TeamSkillMemoryRecallResponse,
  TeamSkillMemoryRecallStatus,
  TeamSkillMemoryTier,
  TeamSkillNotReady,
  TeamSkillOperationStatus,
  TeamSkillOrganization,
  TeamSkillProject,
  TeamSkillProjectAsset,
  TeamSkillProjectDetail,
  TeamSkillReleaseState,
  TeamSkillReleaseStatusItem,
  TeamSkillScope,
  TeamSkillSignature,
  TeamSkillToolPermission,
  TeamSkillTrustAudit,
  TeamSkillTrustCard,
  TeamSkillUninstallRequest,
  TeamSkillUninstallResult,
  TelemetryApprovalDetail,
  TelemetryBatchRequest,
  TelemetryBatchResult,
  TelemetryCompactionDetail,
  TelemetryErrorDetail,
  TelemetryEventAck,
  TelemetryEventDto,
  TelemetryEventKind,
  TelemetryGapDetail,
  TelemetryOutcome,
  TelemetryQueueSettings,
  TelemetryTokenUsage,
} from '../types.ts'
import type {
  AgentAssetBinding,
  AgentExecutionPolicy,
  AgentProfileSummary,
  AgentRunSnapshot,
  AgentRunStatus,
  AgentRunTimelineEntry,
  AgentTypeSchema,
  AgentTypeSchemaField,
  AgentTypeSummary,
  AssetCandidate,
  CloudWorkspace,
  ContextLensDecision,
  ContextLensEntry,
  ContextLensSnapshot,
  ProfileDryRun,
  ProfileEditContext,
  RunApprovalSnapshot,
  RunAssetGovernanceEntry,
  RunAssetSnapshot,
  RunAssetSnapshotEntry,
  RunCheckpointSnapshot,
  RunCheckpointToolResult,
  RunOperationEvidence,
  RunPendingApproval,
  RunPulse,
  RunPulseEntry,
  RunResumeReuseEntry,
  WorkspaceChangeFile,
  WorkspaceChanges,
  WorkspaceCodeSource,
  WorkspaceDirectory,
  WorkspaceFailure,
  WorkspaceFileContent,
  WorkspaceFileEntry,
  WorkspaceLifecycleStatus,
  WorkspacePlan,
  WorkspacePlanEdit,
  WorkspacePlanStep,
  WorkspacePreview,
  WorkspacePreviewUrlGrant,
  WorkspaceProjectedStreamEvent,
  WorkspaceQueryResult,
  WorkspaceStreamEvent,
  WorkspaceStreamEvents,
  WorkspaceStreamState,
  WorkspaceStreamSubscription,
} from '../workspace-types.ts'

declare module '@deepseek-ai/dsh-typert-protocol' {
  /** Wire namespace `teamSkills`, published by `TeamSkillGateway`. */
  interface TypertRemoteNamespace$teamSkills {
    login: (request: TeamSkillLoginRequest) => Promise<RemoteResult<TeamSkillAccountResult<TeamSkillAccountState>>>
    account: () => Promise<RemoteResult<TeamSkillAccountResult<TeamSkillAccountState>>>
    refreshAccount: () => Promise<RemoteResult<TeamSkillAccountResult<TeamSkillAccountState>>>
    changePassword: (request: TeamSkillChangePasswordRequest) => Promise<RemoteResult<TeamSkillAccountResult<TeamSkillAccountState>>>
    logout: () => Promise<RemoteResult<TeamSkillAccountResult<TeamSkillAccountState>>>
    accessSummary: () => Promise<RemoteResult<TeamSkillAccountResult<TeamSkillAccessSummary>>>
    projects: () => Promise<RemoteResult<TeamSkillAccountResult<readonly TeamSkillProject[]>>>
    project: (projectId: string) => Promise<RemoteResult<TeamSkillAccountResult<TeamSkillProjectDetail>>>
    catalog: (projectId: string) => Promise<RemoteResult<TeamSkillCatalogResult>>
    knowledgeBases: (projectId: string) => Promise<RemoteResult<TeamSkillAccountResult<readonly TeamSkillKnowledgeBaseSummary[]>>>
    knowledgeSearch: (request: TeamSkillKnowledgeSearchRequest) => Promise<RemoteResult<TeamSkillAccountResult<{ readonly status: 'ready'; readonly response: TeamSkillKnowledgeSearchResponse; }>>>
    knowledgePreview: (knowledgeBaseId: string, documentId: string) => Promise<RemoteResult<TeamSkillAccountResult<TeamSkillKnowledgePreview>>>
    memoryRecall: (request: { readonly projectId: string; readonly query: string; }) => Promise<RemoteResult<TeamSkillAccountResult<TeamSkillMemoryRecallResponse>>>
    memoryCapture: (request: { readonly projectId: string; readonly sessionId: string; readonly taskId?: string; readonly messages: readonly { readonly role: 'user' | 'assistant'; readonly content: string; }[]; }, idempotencyKey: string) => Promise<RemoteResult<TeamSkillAccountResult<TeamSkillMemoryMutation>>>
    memoryList: (request: { readonly projectId: string; readonly keyword?: string; readonly cursor?: string; readonly limit?: number; }) => Promise<RemoteResult<TeamSkillAccountResult<TeamSkillMemoryPage>>>
    memoryCandidatesConfirm: (request: { readonly memoryId: string; readonly expectedRevision: number; }, idempotencyKey: string) => Promise<RemoteResult<TeamSkillAccountResult<TeamSkillMemory>>>
    memoryGet: (memoryId: string) => Promise<RemoteResult<TeamSkillAccountResult<TeamSkillMemory>>>
    memoryUpdate: (request: { readonly memoryId: string; readonly content: string; readonly expectedRevision: number; }, idempotencyKey: string) => Promise<RemoteResult<TeamSkillAccountResult<TeamSkillMemoryMutation>>>
    memoryDelete: (request: { readonly memoryId: string; readonly expectedRevision: number; }, idempotencyKey: string) => Promise<RemoteResult<TeamSkillAccountResult<TeamSkillMemoryMutation>>>
    memoryJobs: (projectId?: string) => Promise<RemoteResult<TeamSkillAccountResult<readonly TeamSkillMemoryJob[]>>>
    memoryAudit: (projectId?: string) => Promise<RemoteResult<TeamSkillAccountResult<readonly TeamSkillMemoryAudit[]>>>
    configureKnowledgeSelection: (sessionId: string, selection: TeamSkillKnowledgeSelection) => Promise<RemoteResult<void>>
    clearKnowledgeSelection: (sessionId: string) => Promise<RemoteResult<void>>
    configureProjectMemory: (sessionId: string, projectId: string) => Promise<RemoteResult<void>>
    clearProjectMemory: (sessionId: string) => Promise<RemoteResult<void>>
    collectorStatus: () => Promise<RemoteResult<CollectorSnapshot>>
    configureCollectorProject: (sessionId: string, projectId: string) => Promise<RemoteResult<CollectorResult<{ readonly projectId: string; }>>>
    clearCollectorProject: (sessionId: string) => Promise<RemoteResult<CollectorResult<{ readonly cleared: true; }>>>
    pauseCollector: () => Promise<RemoteResult<CollectorSnapshot>>
    resumeCollector: () => Promise<RemoteResult<CollectorSnapshot>>
    flushCollector: () => Promise<RemoteResult<CollectorSnapshot>>
    clearPendingCollectorData: () => Promise<RemoteResult<CollectorSnapshot>>
    installations: (projectId: string) => Promise<RemoteResult<readonly TeamSkillInstallationView[] | TeamSkillNotReady | TeamSkillFailed | { readonly status: 'signed-out'; }>>
    syncReleaseStatus: (projectId: string) => Promise<RemoteResult<readonly TeamSkillInstallationView[] | TeamSkillNotReady | TeamSkillFailed | { readonly status: 'signed-out'; }>>
    trustCard: (request: { readonly skillId: string; readonly version: string; readonly projectId: string; }) => Promise<RemoteResult<TeamSkillTrustCard | TeamSkillNotReady | TeamSkillFailed | { readonly status: 'signed-out'; }>>
    installSkill: (request: TeamSkillInstallRequest) => Promise<RemoteResult<TeamSkillInstallResult>>
    uninstallSkill: (request: TeamSkillUninstallRequest) => Promise<RemoteResult<TeamSkillUninstallResult>>
  }
  /** Wire namespace `cloudWorkspaces`, published by `WorkspaceGateway`. */
  interface TypertRemoteNamespace$cloudWorkspaces {
    agentTypes: () => Promise<RemoteResult<WorkspaceQueryResult<readonly AgentTypeSummary[]>>>
    agentProfiles: (projectId: string) => Promise<RemoteResult<WorkspaceQueryResult<readonly AgentProfileSummary[]>>>
    agentProfileVersion: (versionId: string) => Promise<RemoteResult<WorkspaceQueryResult<AgentProfileSummary>>>
    agentTypeSchema: (agentTypeId: string) => Promise<RemoteResult<WorkspaceQueryResult<AgentTypeSchema>>>
    codeSources: (projectId: string) => Promise<RemoteResult<WorkspaceQueryResult<readonly WorkspaceCodeSource[]>>>
    workspaces: (projectId: string) => Promise<RemoteResult<WorkspaceQueryResult<readonly CloudWorkspace[]>>>
    workspace: (workspaceId: string) => Promise<RemoteResult<WorkspaceQueryResult<CloudWorkspace>>>
    workspaceFiles: (workspaceId: string, path: string) => Promise<RemoteResult<WorkspaceQueryResult<WorkspaceDirectory>>>
    workspaceFileContent: (workspaceId: string, path: string) => Promise<RemoteResult<WorkspaceQueryResult<WorkspaceFileContent>>>
    workspaceChanges: (workspaceId: string) => Promise<RemoteResult<WorkspaceQueryResult<WorkspaceChanges>>>
    workspacePreview: (workspaceId: string, path: string) => Promise<RemoteResult<WorkspaceQueryResult<WorkspacePreview>>>
    workspacePreviewUrl: (workspaceId: string, appPort: number) => Promise<RemoteResult<WorkspaceQueryResult<WorkspacePreviewUrlGrant>>>
    createWorkspace: (input: { readonly projectId: string; readonly repositoryId: string; readonly branch: string; readonly agentProfileVersionId: string; readonly displayName?: string; }) => Promise<RemoteResult<WorkspaceQueryResult<CloudWorkspace>>>
    workspaceAction: (workspaceId: string, action: 'start' | 'stop' | 'retry' | 'archive', expectedRevision?: number) => Promise<RemoteResult<WorkspaceQueryResult<CloudWorkspace>>>
    deleteWorkspace: (workspaceId: string, expectedRevision: number) => Promise<RemoteResult<WorkspaceQueryResult<CloudWorkspace>>>
    createPullRequest: (workspaceId: string, title: string, expectedRevision: number) => Promise<RemoteResult<WorkspaceQueryResult<{ readonly pullRequestId: string; }>>>
    discardChanges: (workspaceId: string, expectedRevision: number) => Promise<RemoteResult<WorkspaceQueryResult<{ readonly revision: number; }>>>
    gitCommit: (workspaceId: string, message: string, expectedRevision: number) => Promise<RemoteResult<WorkspaceQueryResult<{ readonly revision: number; }>>>
    createRun: (input: { readonly workspaceId: string; readonly sessionId: string; readonly writeMode: 'read_only' | 'write'; readonly expectedWorkspaceRevision: number; readonly agentProfileVersionId?: string; readonly planId?: string; }) => Promise<RemoteResult<WorkspaceQueryResult<AgentRunSnapshot>>>
    workspacePlans: (workspaceId: string) => Promise<RemoteResult<WorkspaceQueryResult<readonly WorkspacePlan[]>>>
    plan: (workspaceId: string, planId: string) => Promise<RemoteResult<WorkspaceQueryResult<WorkspacePlan>>>
    createPlan: (input: { readonly workspaceId: string; readonly goal: string; readonly steps: readonly { readonly title: string; readonly dependsOn?: readonly number[]; }[]; readonly agentProfileVersionId: string; readonly assetVersionIds?: readonly string[]; }) => Promise<RemoteResult<WorkspaceQueryResult<WorkspacePlan>>>
    updatePlan: (input: { readonly workspaceId: string; readonly planId: string; readonly goal?: string; readonly steps?: readonly { readonly title: string; readonly dependsOn?: readonly number[]; }[]; readonly agentProfileVersionId?: string; readonly assetVersionIds?: readonly string[]; readonly expectedRevision: number; readonly changeSummary: string; }) => Promise<RemoteResult<WorkspaceQueryResult<WorkspacePlan>>>
    confirmPlan: (input: { readonly workspaceId: string; readonly planId: string; }) => Promise<RemoteResult<WorkspaceQueryResult<WorkspacePlan>>>
    pauseRun: (input: { readonly runId: string; readonly sessionSeq: number; readonly toolResults?: readonly { readonly callId: string; readonly tool: string; readonly result: string; }[]; readonly pendingApproval?: { readonly action: string; readonly summary: string; }; readonly completedSteps?: readonly number[]; }) => Promise<RemoteResult<WorkspaceQueryResult<AgentRunSnapshot>>>
    resumeRun: (input: { readonly runId: string; readonly mode: 'continue' | 'replay'; }) => Promise<RemoteResult<WorkspaceQueryResult<AgentRunSnapshot>>>
    runCheckpoint: (runId: string, checkpointId?: string) => Promise<RemoteResult<WorkspaceQueryResult<RunCheckpointSnapshot>>>
    runPulse: (runId: string) => Promise<RemoteResult<WorkspaceQueryResult<RunPulse>>>
    contextLens: (workspaceId: string, runId?: string) => Promise<RemoteResult<WorkspaceQueryResult<ContextLensSnapshot>>>
    suppressContextLensMemory: (workspaceId: string, runId: string, memoryId: string, suppressed: boolean) => Promise<RemoteResult<WorkspaceQueryResult<ContextLensSnapshot>>>
    runAssetSnapshot: (runId: string) => Promise<RemoteResult<WorkspaceQueryResult<RunAssetSnapshot>>>
    profileEditContext: (profileId: string) => Promise<RemoteResult<WorkspaceQueryResult<ProfileEditContext>>>
    assetCandidates: (projectId: string) => Promise<RemoteResult<WorkspaceQueryResult<readonly AssetCandidate[]>>>
    dryRunProfile: (input: { readonly profileId: string; readonly versionId: string; }) => Promise<RemoteResult<WorkspaceQueryResult<ProfileDryRun>>>
    createProfileVersion: (input: { readonly profileId: string; readonly expectedRevision: number; }) => Promise<RemoteResult<WorkspaceQueryResult<ProfileEditContext>>>
    updateProfileDraft: (input: { readonly profileId: string; readonly expectedRevision: number; readonly patch: { readonly name?: string; readonly description?: string; readonly model?: string; readonly reasoning?: string; }; }) => Promise<RemoteResult<WorkspaceQueryResult<ProfileEditContext>>>
    publishProfileVersion: (input: { readonly profileId: string; readonly versionId: string; readonly expectedRevision: number; }) => Promise<RemoteResult<WorkspaceQueryResult<ProfileEditContext>>>
    workspaceRuns: (workspaceId: string) => Promise<RemoteResult<WorkspaceQueryResult<readonly AgentRunSnapshot[]>>>
    run: (runId: string) => Promise<RemoteResult<WorkspaceQueryResult<AgentRunSnapshot>>>
    runApproval: (runId: string) => Promise<RemoteResult<WorkspaceQueryResult<RunApprovalSnapshot>>>
    decideApproval: (input: { readonly runId: string; readonly decision: 'approve' | 'reject'; readonly expectedRunRevision: number; }) => Promise<RemoteResult<WorkspaceQueryResult<AgentRunSnapshot>>>
    takeoverRun: (input: { readonly runId: string; readonly expectedRunRevision: number; }) => Promise<RemoteResult<WorkspaceQueryResult<AgentRunSnapshot>>>
    cancelRun: (runId: string) => Promise<RemoteResult<WorkspaceQueryResult<AgentRunSnapshot>>>
    retryRun: (runId: string, expectedWorkspaceRevision: number) => Promise<RemoteResult<WorkspaceQueryResult<AgentRunSnapshot>>>
    streamState: (subscriptionId: string) => Promise<RemoteResult<WorkspaceStreamState>>
    startStream: (scope: { readonly projectId: string; readonly workspaceId?: string; readonly lastEventId?: string; }) => Promise<RemoteResult<WorkspaceStreamSubscription>>
    stopStream: (subscriptionId: string) => Promise<RemoteResult<WorkspaceStreamState>>
    streamEventsAfter: (subscriptionId: string, afterEventId: string) => Promise<RemoteResult<WorkspaceStreamEvents>>
  }
  /** Remote namespaces this plugin contributes to the assembled client face. */
  interface TypertRemoteNamespaceMap {
    'teamSkills': TypertRemoteNamespace$teamSkills
    'cloudWorkspaces': TypertRemoteNamespace$cloudWorkspaces
  }
}
